apiVersion: v1
kind: Service
metadata:
  name: tainux-doctor-ui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tainux-doctor-ui
  ports:
    - name: http
      port: 8080
      targetPort: http
